/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../components/table/ng-table.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import9 from '@angular/core/src/linker/component_factory_resolver';
import * as import10 from '@angular/core/src/linker/compiler';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/common/src/directives/ng_style';
import * as import14 from '@angular/common/src/directives/ng_class';
import * as import15 from '@angular/common/src/directives/ng_if';
import * as import16 from '@angular/common/src/directives/ng_for';
import * as import17 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '../../../components/table/ng-table-sorting.directive';
import * as import22 from '../../../components/table/ng-table-filtering.directive';
import * as import23 from '@angular/core/src/security';
import * as import24 from '../../../components/table/ng-table-row.component';
import * as import25 from './ng-table-row.component.ngfactory';
var renderType_NgTableComponent_Host:import0.RenderComponentType = (null as any);
class _View_NgTableComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _NgTableComponent_0_4:import3.NgTableComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent_Host0,renderType_NgTableComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-table',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NgTableComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NgTableComponent_0_4 = new import3.NgTableComponent(this.parentInjector.get(import8.DomSanitizer),compView_0.ref,this.parentInjector.get(import9.ComponentFactoryResolver),this.parentInjector.get(import10.Compiler));
    this._appEl_0.initComponent(this._NgTableComponent_0_4,[],compView_0);
    compView_0.create(this._NgTableComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.NgTableComponent) && (0 === requestNodeIndex))) { return this._NgTableComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_NgTableComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_NgTableComponent_Host === (null as any))) { (renderType_NgTableComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_NgTableComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NgTableComponentNgFactory:import12.ComponentFactory<import3.NgTableComponent> = new import12.ComponentFactory<import3.NgTableComponent>('ng-table',viewFactory_NgTableComponent_Host0,import3.NgTableComponent);
const styles_NgTableComponent:any[] = [];
var renderType_NgTableComponent:import0.RenderComponentType = (null as any);
class _View_NgTableComponent0 extends import1.AppView<import3.NgTableComponent> {
  _text_0:any;
  _el_1:any;
  _NgStyle_1_3:import13.NgStyle;
  _text_2:any;
  _el_3:any;
  _NgClass_3_3:import14.NgClass;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import15.NgIf;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgFor_11_6:import16.NgFor;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import15.NgIf;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import16.NgFor;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent0,renderType_NgTableComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'style','overflow-y:scroll; width:auto; overflow-x:hidden; display:block;');
    this._NgStyle_1_3 = new import13.NgStyle(this.parentInjector.get(import17.KeyValueDiffers),new import18.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'table',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','table dataTable');
    this.renderer.setElementAttribute(this._el_3,'role','grid');
    this.renderer.setElementAttribute(this._el_3,'style','width: 100%;');
    this._NgClass_3_3 = new import14.NgClass(this.parentInjector.get(import19.IterableDiffers),this.parentInjector.get(import17.KeyValueDiffers),new import18.ElementRef(this._el_3),this.renderer);
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'thead',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'tr',(null as any));
    this.renderer.setElementAttribute(this._el_7,'role','row');
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import20.TemplateRef_(this._appEl_9,viewFactory_NgTableComponent1);
    this._NgIf_9_6 = new import15.NgIf(this._appEl_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_11 = new import2.AppElement(11,7,this,this._anchor_11);
    this._TemplateRef_11_5 = new import20.TemplateRef_(this._appEl_11,viewFactory_NgTableComponent2);
    this._NgFor_11_6 = new import16.NgFor(this._appEl_11.vcRef,this._TemplateRef_11_5,this.parentInjector.get(import19.IterableDiffers),this.ref);
    this._text_12 = this.renderer.createText(this._el_7,'\n          ',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_3,'tbody',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_17 = new import2.AppElement(17,15,this,this._anchor_17);
    this._TemplateRef_17_5 = new import20.TemplateRef_(this._appEl_17,viewFactory_NgTableComponent4);
    this._NgIf_17_6 = new import15.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_19 = new import2.AppElement(19,15,this,this._anchor_19);
    this._TemplateRef_19_5 = new import20.TemplateRef_(this._appEl_19,viewFactory_NgTableComponent8);
    this._NgFor_19_6 = new import16.NgFor(this._appEl_19.vcRef,this._TemplateRef_19_5,this.parentInjector.get(import19.IterableDiffers),this.ref);
    this._text_20 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._text_22 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'scroll',this.eventHandler(this._handle_scroll_1_0.bind(this)));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {height: p0};
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import15.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6; }
    if (((token === import20.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import16.NgFor) && (11 === requestNodeIndex))) { return this._NgFor_11_6; }
    if (((token === import20.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import15.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    if (((token === import20.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import16.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6; }
    if (((token === import14.NgClass) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._NgClass_3_3; }
    if (((token === import13.NgStyle) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgStyle_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_1:any = this._map_0(((this.context.config == (null as any))? (null as any): this.context.config.height));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgStyle_1_3.ngStyle = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgStyle_1_3.ngDoCheck(); }
    const currVal_2:any = 'table dataTable';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_3_3.klass = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',(this.context.config.className || ''),'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgClass_3_3.ngClass = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (!throwOnChange) { this._NgClass_3_3.ngDoCheck(); }
    const currVal_4:any = this.context.expandable;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_9_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    changes = (null as any);
    const currVal_5:any = this.context.columns;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgFor_11_6.ngForOf = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._NgFor_11_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_11_6.ngDoCheck(); }
    const currVal_6:any = this.context.showFilterRow;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_17_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    changes = (null as any);
    const currVal_7:any = this.context.rows;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgFor_19_6.ngForOf = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._NgFor_19_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_19_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_scroll_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.checkScroll($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_NgTableComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.NgTableComponent> {
  if ((renderType_NgTableComponent === (null as any))) { (renderType_NgTableComponent = viewUtils.createRenderComponentType('C:/Users/Austin/webdev/ng2-expanding-table/components/table/ng-table.component.ts class NgTableComponent - inline template',0,import11.ViewEncapsulation.None,styles_NgTableComponent,{})); }
  return new _View_NgTableComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent1 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent1,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'th',(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_NgTableComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent2 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import14.NgClass;
  _NgTableSortingDirective_0_4:import21.NgTableSortingDirective;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import15.NgIf;
  _text_3:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent2,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'th',(null as any));
    this._NgClass_0_3 = new import14.NgClass(this.parent.parentInjector.get(import19.IterableDiffers),this.parent.parentInjector.get(import17.KeyValueDiffers),new import18.ElementRef(this._el_0),this.renderer);
    this._NgTableSortingDirective_0_4 = new import21.NgTableSortingDirective();
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this._appEl_2,viewFactory_NgTableComponent3);
    this._NgIf_2_6 = new import15.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'sortChanged',this.eventHandler(this._handle_sortChanged_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgTableSortingDirective_0_4.sortChanged.subscribe(this.eventHandler(this._handle_sortChanged_0_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import15.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import14.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgClass_0_3; }
    if (((token === import21.NgTableSortingDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgTableSortingDirective_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import4.interpolate(1,'',(this.context.$implicit.className || ''),'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_0_3.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    const currVal_3:any = this.parent.context.config;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgTableSortingDirective_0_4.ngTableSorting = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgTableSortingDirective_0_4.column = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = (this.parent.context.config && this.context.$implicit.sort);
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_2_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_5:any = import4.interpolate(1,'\n              ',this.context.$implicit.title,'\n              ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_1,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_sortChanged_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onChangeTable($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgTableSortingDirective_0_4.onToggleSort($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NgTableComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent3 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import14.NgClass;
  /*private*/ _expr_0:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent3,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'i',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','pull-right fa');
    this._NgClass_0_3 = new import14.NgClass(this.parent.parent.parentInjector.get(import19.IterableDiffers),this.parent.parent.parentInjector.get(import17.KeyValueDiffers),new import18.ElementRef(this._el_0),this.renderer);
    this._expr_0 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'fa-chevron-down': p0,
        'fa-chevron-up': p1
      }
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.NgClass) && (0 === requestNodeIndex))) { return this._NgClass_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'pull-right fa';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_0_3.klass = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._map_0((this.parent.context.$implicit.sort === 'desc'),(this.parent.context.$implicit.sort === 'asc'));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_0_3.ngClass = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NgTableComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import15.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgFor_4_6:import16.NgFor;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent4,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this._appEl_2,viewFactory_NgTableComponent5);
    this._NgIf_2_6 = new import15.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import20.TemplateRef_(this._appEl_4,viewFactory_NgTableComponent6);
    this._NgFor_4_6 = new import16.NgFor(this._appEl_4.vcRef,this._TemplateRef_4_5,this.parent.parentInjector.get(import19.IterableDiffers),this.parent.ref);
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import15.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import20.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import16.NgFor) && (4 === requestNodeIndex))) { return this._NgFor_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = this.parent.context.expandable;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    changes = (null as any);
    const currVal_1:any = this.parent.context.columns;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_4_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_4_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_4_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NgTableComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent5 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent5,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'td',(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_NgTableComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import15.NgIf;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent6,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'td',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this._appEl_2,viewFactory_NgTableComponent7);
    this._NgIf_2_6 = new import15.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import15.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit.filtering;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NgTableComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent7 extends import1.AppView<any> {
  _el_0:any;
  _NgTableFilteringDirective_0_3:import22.NgTableFilteringDirective;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent7,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'input',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','form-control');
    this.renderer.setElementAttribute(this._el_0,'style','width: 85%; padding:none;');
    this._NgTableFilteringDirective_0_3 = new import22.NgTableFilteringDirective(new import18.ElementRef(this._el_0),this.renderer);
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'tableChanged',this.eventHandler(this._handle_tableChanged_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'input',this.eventHandler(this._handle_input_0_1.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgTableFilteringDirective_0_3.tableChanged.subscribe(this.eventHandler(this._handle_tableChanged_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.NgTableFilteringDirective) && (0 === requestNodeIndex))) { return this._NgTableFilteringDirective_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = this.parent.context.$implicit.filtering;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgTableFilteringDirective_0_3.ngTableFiltering = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'',this.parent.context.$implicit.filtering.placeholder,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'placeholder',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_tableChanged_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.onChangeTable(this.parent.parent.parent.context.config)) !== false);
    return (true && pd_0);
  }
  private _handle_input_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgTableFilteringDirective_0_3.onChangeFilter($event.target.value)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NgTableComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent8 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import14.NgClass;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import15.NgIf;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _TemplateRef_5_5:any;
  _NgFor_5_6:import16.NgFor;
  _text_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import15.NgIf;
  _text_9:any;
  _map_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent8,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'tr',(null as any));
    this._NgClass_1_3 = new import14.NgClass(this.parent.parentInjector.get(import19.IterableDiffers),this.parent.parentInjector.get(import17.KeyValueDiffers),new import18.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_3 = new import2.AppElement(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import20.TemplateRef_(this._appEl_3,viewFactory_NgTableComponent9);
    this._NgIf_3_6 = new import15.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_5 = new import2.AppElement(5,1,this,this._anchor_5);
    this._TemplateRef_5_5 = new import20.TemplateRef_(this._appEl_5,viewFactory_NgTableComponent10);
    this._NgFor_5_6 = new import16.NgFor(this._appEl_5.vcRef,this._TemplateRef_5_5,this.parent.parentInjector.get(import19.IterableDiffers),this.parent.ref);
    this._text_6 = this.renderer.createText(this._el_1,'\n          ',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_8 = new import2.AppElement(8,(null as any),this,this._anchor_8);
    this._TemplateRef_8_5 = new import20.TemplateRef_(this._appEl_8,viewFactory_NgTableComponent11);
    this._NgIf_8_6 = new import15.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {'table-info': p0};
    });
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_7,
      this._appEl_8,
      this._text_9
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._text_7,
      this._anchor_8,
      this._text_9
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import15.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    if (((token === import20.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import16.NgFor) && (5 === requestNodeIndex))) { return this._NgFor_5_6; }
    if (((token === import14.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._NgClass_1_3; }
    if (((token === import20.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import15.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = this._map_0(((this.parent.context.showExpandedRow && (this.context.index == this.parent.context.expandedRowIndex)) && this.parent.context.expandable));
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_1_3.ngClass = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (!throwOnChange) { this._NgClass_1_3.ngDoCheck(); }
    const currVal_1:any = this.parent.context.expandable;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_3_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    changes = (null as any);
    const currVal_2:any = this.parent.context.columns;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_5_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_5_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_5_6.ngDoCheck(); }
    const currVal_3:any = ((this.parent.context.showExpandedRow && (this.context.index == this.parent.context.expandedRowIndex)) && this.parent.context.expandable);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_8_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NgTableComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent9 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _NgClass_3_3:import14.NgClass;
  _text_4:any;
  _map_0:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent9,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'td',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','text-align:center; padding:0px; padding-top:7px;');
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_1,'style','width:100%; text-align:center;');
    this._text_2 = this.renderer.createText(this._el_1,'\n              ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'i',(null as any));
    this.renderer.setElementAttribute(this._el_3,'style','font-size:1.5em; cursor:pointer');
    this._NgClass_3_3 = new import14.NgClass(this.parent.parent.parentInjector.get(import19.IterableDiffers),this.parent.parent.parentInjector.get(import17.KeyValueDiffers),new import18.ElementRef(this._el_3),this.renderer);
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._map_0 = import4.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        fa: p0,
        'fa-plus-circle': p1,
        'fa-minus-circle': p2
      }
      ;
    });
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.NgClass) && (3 === requestNodeIndex))) { return this._NgClass_3_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this._map_0(true,(this.parent.context.index != this.parent.parent.context.expandedRowIndex),(this.parent.context.index == this.parent.parent.context.expandedRowIndex));
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_3_3.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_3_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.toggleRowExpansion(this.parent.context.$implicit,this.parent.context.index)) !== false);
    const pd_1:any = ((<any>this.parent.parent.context.cellClick(this.parent.context.$implicit,'expand',this.parent.context.index)) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_NgTableComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent9(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent10 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent10,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'td',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.parent.parent.context.sanitize(this.parent.parent.context.getData(this.parent.context.$implicit,this.context.$implicit.name));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.cellClick(this.parent.context.$implicit,this.context.$implicit.name,this.parent.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NgTableComponent10(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent10(viewUtils,parentInjector,declarationEl);
}
class _View_NgTableComponent11 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _NgTableRowComponent_4_4:import24.NgTableRowComponent;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NgTableComponent11,renderType_NgTableComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','table-info');
    this._text_1 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ng-table-row',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import25.viewFactory_NgTableRowComponent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._NgTableRowComponent_4_4 = new import24.NgTableRowComponent(this.parent.parent.parentInjector.get(import9.ComponentFactoryResolver),this.parent.parent.parentInjector.get(import10.Compiler),compView_4.ref);
    this._appEl_4.initComponent(this._NgTableRowComponent_4_4,[],compView_4);
    compView_4.create(this._NgTableRowComponent_4_4,[],(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n              ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.NgTableRowComponent) && (4 === requestNodeIndex))) { return this._NgTableRowComponent_4_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this.parent.parent.context.expandedComponent;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgTableRowComponent_4_4.rowComponent = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['rowComponent'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgTableRowComponent_4_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = (this.parent.parent.context.columns.length + 1);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementAttribute(this._el_2,'colspan',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._NgTableRowComponent_4_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgTableRowComponent_4_4.ngOnDestroy();
  }
}
function viewFactory_NgTableComponent11(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NgTableComponent11(viewUtils,parentInjector,declarationEl);
}